### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by geek1011** [StackExchange/dnscontrol#221]
I will work on these sometime soon.

- [x] Code formatting/indentation
- [x] No page titles (#223)
- [x] Not responsive (#223)
- [ ] Some pages are hard to find (improve nav) (#236)
- [ ] Some pages could use some styling improvements (#236)
- [X] Documentation is inconsistent (#222) (#224) (#226) (#227) (#228) (#229) (#230) (#231) (#232) (#233) (#234) (#235)
- [X] Various documentation issues (#224) (#225) (#226) (#227) (#228) (#229) (#230) (#231) (#232) (#233) (#234) (#235)

I will add to this list as I encounter more issues.

**Comment by tlimoncelli** [comment]
I think you've done enough to consider this closed.  We can split anything else into a separate bug, eh?

**Comment by geek1011** [comment]
Yep. Basically only the nav is left (it's still slightly confusing).
